

try:
	#~ raise Exception("a")
	pass
except Exception, e:
	print e
#~ finally:
	#~ print 'aaa'
	bbb
